<?php
// Generated by Gemini

// Usamos las variables de entorno estándar de AWS RDS
$host = $_SERVER['RDS_HOSTNAME'] ?? 'localhost';
$db   = $_SERVER['RDS_DB_NAME']  ?? 'ebdb';
$user = $_SERVER['RDS_USERNAME'] ?? 'admin';
$pass = $_SERVER['RDS_PASSWORD'] ?? '';
$port = $_SERVER['RDS_PORT']     ?? '3306';

$dsn = "mysql:host=$host;dbname=$db;port=$port;charset=utf8mb4";

try {
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
} catch (PDOException $e) {
    die("Error de conexión: " . $e->getMessage());
}
?>