<?php
// Generated by Gemini

// Mostrar información para verificar que se carga el código
print("<br><br>Hola, bienvenvido/da a la aplicación de prueba PHP - Beanstalk<br>");
print("<br><br>Esta es la versión 1 de la aplicación<br>");
// Mostrar las variables de entorno
print("<br>Variables de entorno definidas:<br>");
echo "<pre>";
print_r($_SERVER);
echo "</pre>";

require_once 'db.php';

// Procesar el formulario si se ha enviado
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST['nombre'])) {
    $stmt = $pdo->prepare("INSERT INTO contactos (nombre, email) VALUES (?, ?)");
    $stmt->execute([$_POST['nombre'], $_POST['email']]);
    header("Location: index.php");
    exit();
}

// Obtener todos los contactos
$contactos = $pdo->query("SELECT * FROM contactos ORDER BY id DESC")->fetchAll();
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Agenda PHP en AWS</title>
    <style>
        body { font-family: sans-serif; background: #f4f4f4; padding: 20px; }
        .container { max-width: 500px; background: white; padding: 20px; margin: auto; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        input { width: 100%; padding: 10px; margin: 10px 0; box-sizing: border-box; }
        button { background: #ff9900; border: none; padding: 10px; width: 100%; cursor: pointer; font-weight: bold; }
        ul { list-style: none; padding: 0; }
        li { background: #eee; margin: 5px 0; padding: 10px; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Agenda de Contactos</h1>
        
        <form method="POST">
            <input type="text" name="nombre" placeholder="Nombre completo" required>
            <input type="email" name="email" placeholder="Correo electrónico">
            <button type="submit">Añadir Contacto</button>
        </form>

        <hr>

        <h2>Contactos Registrados</h2>
        <ul>
            <?php foreach ($contactos as $c): ?>
                <li>
                    <strong><?= htmlspecialchars($c['nombre']) ?></strong><br>
                    <small><?= htmlspecialchars($c['email']) ?></small>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>